### ISSUE TITLE
Claim Android port

### ISSUE THREAD

**Issue by robertying** [ThomasLee969/CampNet#11]
I've been using this app and it's really amazing!

I would love to open an Android port and may use the same name (to be decided...), probably the same icon and UIs.

It would be great if it were possible. Thanks again for the efforts!

**Comment by ClumsyLee** [comment]
Hi Robert,

Sure, I'd love to see an Android port! This project is MIT licensed, so you are free to do so as long as you include the license in your binary. Actually, if you want to use the same name "CampNet", I would even recommend you to use the same icon/UIs, so that the Android users can have the same experiences with the iOS users.

However, if you want to use the same name "CampNet", I really wish we can do this together to make sure we get it right. For example, "universal" is one of the top priorities in CampNet. The network configurations ([ClumsyLee/CampNet-Configurations](https://github.com/ClumsyLee/CampNet-Configurations)) are completely separated from the UI, so that we can support more campuses in the future (right now we support three). So I really wish all the "CampNet" clients (iOS, Android, or even desktops) can use the same configuration files.

That being said, would you like to join the WeChat group for CampNet development? Don't worry, you don't have to develop anything by joining the group!

![campnet-development-wechat-group](https://user-images.githubusercontent.com/7030671/52971197-6b866d80-336b-11e9-8116-0b05ab97affe.jpeg)
